<?php
defined('ABSPATH') || exit;

/**
 * Production Plan Manager
 *
 * Handles fetching production plans generated by the Coordinator and submitting
 * explicit user approvals before production execution is queued in Django.
 */
class Tersuite_AI_Production_Plan_Manager {

    private $api;

    public function __construct() {
        $this->api = new Tersuite_AI_API_Client();
    }

    /**
     * Get production plans or a specific plan.
     *
     * @param string|int $project_id
     * @param string|null $plan_id
     * @return array|WP_Error
     */
    public function get($project_id, $plan_id = null) {
        if (empty($project_id)) {
            return new WP_Error('missing_project_id', __('Project ID is required to load production plans.', 'tersuite-ai-studio'));
        }

        $path = 'api/v1/projects/' . rawurlencode((string) $project_id) . '/production-plans';
        if ($plan_id !== null && $plan_id !== '') {
            $path .= '/' . rawurlencode((string) $plan_id);
        }

        return $this->api->get($path);
    }

    /**
     * Submit explicit user approval for a production plan.
     *
     * @param string|int $project_id
     * @param string|int $plan_id
     * @return array|WP_Error
     */
    public function approve($project_id, $plan_id) {
        if (empty($project_id) || empty($plan_id)) {
            return new WP_Error('invalid_params', __('Project ID and Plan ID are required to approve production.', 'tersuite-ai-studio'));
        }

        $path = 'api/v1/projects/' . rawurlencode((string) $project_id) . '/production-plans/' . rawurlencode((string) $plan_id) . '/approve';
        return $this->api->post($path);
    }
}
