# Generated by Django 5.0
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("api_base_url", models.URLField()),
                ("api_key_env_var", models.CharField(max_length=200, help_text="Environment variable name that holds the API key (e.g., OPENAI_API_KEY)")),
                ("enabled", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Provider",
                "verbose_name_plural": "LLM Providers",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_id", models.CharField(max_length=200, help_text="Actual API model identifier (e.g., gpt-5.6-sol)")),
                ("display_name", models.CharField(max_length=200)),
                ("version_tag", models.CharField(default="latest", max_length=50, help_text="e.g., '2026-07', 'v1.0'")),
                ("is_default", models.BooleanField(default=False)),
                ("is_latest", models.BooleanField(default=True)),
                ("capabilities", models.CharField(default="coding,reasoning,agentic", max_length=500, help_text="Comma-separated capabilities (coding,security,ui,frontend,backend,review)")),
                ("max_tokens", models.PositiveIntegerField(default=128000)),
                ("cost_input_per_million", models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ("cost_output_per_million", models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ("enabled", models.BooleanField(default=True)),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="models", to="llm_registry.llmprovider")),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "ordering": ["provider", "-is_latest", "-is_default"],
                "unique_together": {("provider", "model_id")},
            },
        ),
    ]
