<?php defined('ABSPATH') || exit; ?>
<div class="wrap tsa-wrap">
<?php include TERSUITE_AI_DIR.'admin/partials/sidebar.php'; ?>
<div class="tsa-main"><div class="tsa-topbar-spacer"></div><?php include TERSUITE_AI_DIR.'admin/partials/header.php'; ?>
<div class="tsa-content"><div class="tsa-page-head"><div><h1>Dashboard</h1><p>Everything happening across your Tersuite workspace.</p></div><a class="tsa-primary" href="<?php echo esc_url(admin_url('admin.php?page=tersuite-ai-projects')); ?>">+ New Project</a></div>
<div class="tsa-stats-grid"><div class="tsa-stat-card"><span>Projects</span><strong>18</strong><small>+4 this month</small></div><div class="tsa-stat-card"><span>Generations</span><strong>37</strong><small>31 completed</small></div><div class="tsa-stat-card"><span>Credits</span><strong>842</strong><small>158 remaining</small></div><div class="tsa-stat-card"><span>Success Rate</span><strong>96%</strong><small>+3.2% this month</small></div></div>
<div class="tsa-dashboard-grid"><section class="tsa-panel tsa-current"><div class="tsa-panel-head"><div><span class="tsa-kicker">CURRENT GENERATION</span><h2>Membership Manager</h2></div><span class="tsa-status-chip live">RUNNING</span></div><div class="tsa-overall"><div><strong>65%</strong><span>overall progress</span></div><div class="tsa-progress big"><span style="width:65%"></span></div><small>Estimated remaining 00:02:15</small></div><div class="tsa-mini-agents"><div class="ok">✓ Coordinator</div><div class="ok">✓ Planner</div><div class="ok">✓ UI/UX</div><div class="active">● Backend</div><div>○ Security</div><div>○ Coder</div></div><a class="tsa-secondary" href="<?php echo esc_url(admin_url('admin.php?page=tersuite-ai-ai-studio')); ?>">Open AI Studio →</a></section>
<section class="tsa-panel"><div class="tsa-panel-head"><div><span class="tsa-kicker">RECENT PROJECTS</span><h2>Your workspace</h2></div><a href="<?php echo esc_url(admin_url('admin.php?page=tersuite-ai-projects')); ?>">View all</a></div><div class="tsa-project-list"><div class="tsa-project-row"><span class="tsa-folder-icon">◆</span><div><strong>Membership Manager</strong><small>Updated 4 min ago</small></div><span class="tsa-status-chip live">Generating</span></div><div class="tsa-project-row"><span class="tsa-folder-icon">◆</span><div><strong>Invoice System</strong><small>Updated yesterday</small></div><span class="tsa-status-chip success">Ready</span></div><div class="tsa-project-row"><span class="tsa-folder-icon">◆</span><div><strong>Event Registration</strong><small>Updated 3 days ago</small></div><span class="tsa-status-chip neutral">Archived</span></div></div></section></div>
<div class="tsa-dashboard-grid bottom"><section class="tsa-panel"><div class="tsa-panel-head"><div><span class="tsa-kicker">ACTIVITY</span><h2>Latest events</h2></div><a href="<?php echo esc_url(admin_url('admin.php?page=tersuite-ai-activity')); ?>">See all</a></div><div class="tsa-activity-list"><div><span class="tsa-event-dot success"></span><p><strong>Sandbox passed</strong><br><small>Membership Manager · 2 min ago</small></p></div><div><span class="tsa-event-dot"></span><p><strong>Backend Agent completed</strong><br><small>Membership Manager · 4 min ago</small></p></div><div><span class="tsa-event-dot"></span><p><strong>Credits purchased</strong><br><small>500 credits · Yesterday</small></p></div></div></section><section class="tsa-panel"><div class="tsa-panel-head"><div><span class="tsa-kicker">SYSTEM</span><h2>Connection health</h2></div></div><div class="tsa-health"><div><span class="health-dot good"></span>Django API <strong>Healthy</strong></div><div><span class="health-dot good"></span>WebSocket <strong>Healthy</strong></div><div><span class="health-dot good"></span>Authentication <strong>Connected</strong></div><div><span class="health-dot warn"></span>Sandbox <strong>Standby</strong></div></div></section></div></div></div></div>
