<?php defined('ABSPATH') || exit; ?>
<div class="wrap tsa-wrap"><div class="tsa-main-full">
<?php include TERSUITE_AI_DIR.'admin/partials/sidebar.php'; ?><div class="tsa-main"><div class="tsa-topbar-spacer"></div><?php include TERSUITE_AI_DIR.'admin/partials/header.php'; ?>
<div class="tsa-content">
 <div class="tsa-page-head"><div><h1>Projects</h1><p>Build, manage and version your AI-generated WordPress projects.</p></div><button class="tsa-primary" id="tsa-create-project" type="button">+ New Project</button></div>
 <div class="tsa-toolbar"><input class="tsa-search" placeholder="Search projects…" id="tsa-project-search" type="search"><select class="tsa-select" id="tsa-project-status"><option value="">All statuses</option><option value="generating">Generating</option><option value="ready">Ready</option><option value="failed">Failed</option><option value="archived">Archived</option></select><div class="tsa-spacer"></div><button class="tsa-icon-btn is-active" id="tsa-grid-view" type="button">▦</button><button class="tsa-icon-btn" id="tsa-list-view" type="button">☷</button></div>
 <div id="tsa-projects-list" class="tsa-project-cards"><div class="tsa-loading-state"><span class="tsa-spinner"></span>Loading projects…</div></div>
</div></div></div></div>
<div class="tsa-modal-overlay" id="tsa-project-modal" hidden><div class="tsa-modal-card tsa-form-modal"><button class="tsa-modal-close" id="tsa-project-modal-close" type="button">×</button><h2>Create project</h2><p>Describe the project briefly. The Coordinator will use this as the initial project context.</p><form id="tsa-create-project-form"><div id="tsa-project-form-status" class="tsa-form-status" role="status" aria-live="polite" hidden></div><label>Project name<input id="tsa-proj-name" required maxlength="120"></label><label>Description<textarea id="tsa-proj-desc" rows="5" maxlength="2000" placeholder="What should this WordPress project do?"></textarea></label><div class="tsa-modal-actions"><button type="button" class="tsa-secondary" id="tsa-project-cancel">Cancel</button><button type="submit" class="tsa-primary">Create & Open Studio</button></div></form></div></div>
